### PR TITLE
Added profile shift capabilities

### PR DESCRIPTION
**Pull request by kavers1**
Hi, I have added profile shift capabalities. 
You can enter the profile shift coefficient manually or you can use the no undercut check mark to calculate the shift coefficient to avoid the undercut in case of gears with less than 17 teeth.
I have added info to the web pages I used to understand this.

### CODE REVIEW

**Comment by kavers1** [comment]
#17

**Comment by phossystems** [comment]
Awesome, very cool!
A few things I would want to add:

- Since profile shifting changes the center distance it would be nice to have the working pitch diameter (I think that's what its called) instead of the regular pitch diameter in the pitch diameter sketch.
 - Also working pitch diameter would be a nice addition in the info section
 - The no undercut checkbox does not seem to update the Profile Shift input if the required profile shift is 0
 - The no undercut checkbox seems to uncheck itself every time I change gear parameters like the number of teeth. (If this is intensional it may be better to use a button instead of a checkbox, but I think it would be better to just update the profile shift every time gear parameters change when the no undercut checkbox is checked)

**Comment by kavers1** [comment]
- I have been thinking about the working pitch diameter but this can't be done without knowing what the engaging gears parameters are. E.g. if engaged with a rack the pitch diameter does not change. If engaged with another gear it does change but it then depends on the number of teeth and the profileshift coefficient of the the engaging gear. (see formula 40 on https://www.tec-science.com/mechanical-power-transmission/involute-gear/calculation-of-involute-gears/). 
So I have not solution for this. 
- I would like to add functionality to calculate the profile shift to get a given center to center distance but then we need to have info of the second gear too. This could be done by adding a new tab page.

- you are correct the checkbox should be replaced by a button. Since all this, fusion add-ins and python are new to me I used the easy way to get at least some results. I'll replace the checkbox by a button.
- if the number of theeth is above the threshold of undercut taking into account the provided profile shift, no new profile shift is calculated. As pointed out above a button will take away this confusion. The button could be disabled if the gear has no undercut.

**Comment by phossystems** [comment]
Interesting. I did not know that I thought the increase in center distance was just x * m but I can now see why that is inaccurate.

I am not sure about the second gear tab, that seems like a big change and may confuse users.
We may want to revisit center distance once #18 gets implemented, that seems like the best option.

I think the button should always be enabled but just set the profile shift to 0 if the number of teeth is above the threshold. Let's say:
I create gear with 8 teeth and calculate the profile shift.
I then want to create gear with 40 teeth and press the button again.
This should set the profile shift back to 0, otherwise, the user may think the current profile shift value is required even for 40 teeth.

I will do some slight changes to the button and merge it.
Thank you for your work!

**Pull request closed without merging**
