### PR TITLE
Select plane and origin for gear

### PR DESCRIPTION
**Pull request by lhns**
This PR allows to select a plane and origin for gear creation.
This makes it very easy to stack gears for example.
There are still some problems with my approach because the gear can end up being placed on either side of the plane.
image

### CODE REVIEW

**Comment by lhns** [comment]
Here is another idea for controlling the direction. The "Center" option is not available for rack gears since they are always centered.
image

**Comment by phossystems** [comment]
Nice Idea!
I couldn't actually get it to work, should it? Or is this just to show off the idea?
It ended up somewhere wrong.

Screenshot 2020-03-10 at 19 01 38

Here are my thoughts about how I think this could best be integrated into the Add-In,
Let me know if you like it:

Screenshot 2020-03-10 at 20 36 54

**Separate Positioning tab**
I think between 'Advanced' and 'Properties' fits well into my workflow of creating gear first and then positioning it.
May need icons for tabs since 4 is pretty close to default max-width.

**Origin Selection input**
Can select point-like things
No selection required, uses parent origin if left unselected.

**Plane/Axis Selection input**
Can select Plane-like and Line-Like things
No selection required, uses parent Z+ if left unselected, unless:
origin selection is a sketch point -> Use sketch normal
origin selection is a BRep vertex and is connected to one planar face -> use its normal

**Side/Direction Dropdown**
Same as it is now

**Rotation Angle value**
Rotation of gear around its axis.

**Offset Distance value**
Translation of the gear along its axis

**Additional/Advanced things**
Positioning manipulators should only be visible if the positioning tab is open

Since gear generation is slow it may be nice to look into "caching" the generated gear for smoother visual positioning

Selecting one or two other gear for positioning would also be nice. We could save the pitch diameter as an attribute on the gear component to make this easier


Let me know what you think about my suggestions.


**Btw:**
Helical gear Plus released on the F360 App Store today!
A review would help a lot :)
https://apps.autodesk.com/FUSION/en/Detail/Index?id=1259509007239787473&appLang=en&os=Mac

**Comment by lhns** [comment]
It currently only works for some angles as I still have some of the vector to matrix stuff wrong.
I really like these suggestions. For now though I will try to finish what I currently have and put the positioning options under a separate tab but in future iterations I would love to also add in all the other suggestions.
I also thought about something like an "auto-mesh" feature like you mentioned at the end where you could select another gear and it would orient and rotate the current gear to properly mesh with the selected one. That would definitely be a nice feature in the future.

**Comment by phossystems** [comment]
Definitely!
I may try to do the "moving without recalculating" part, it seems like a fun challenge that should result in a much nicer user experience.

What do you think about taking the "moving" part out of model_gear(), make model_gear() return the component and make a separate function to move it? Performance should be similar, seems cleaner and would make my part easier.

**Comment by phossystems** [comment]
I fixed 99% of the problem:
selectedPlane() and selectedOrigin() where producing garbage most of the time. They still are, but only for ConstructionPoints and ConstructionPlanes one subcomponent deep.

Not a git-wizard so I'll just post it here

```
def selectedPlane(ddPlane):
    planeEntity = ddPlane.selection(0).entity

    if planeEntity.objectType == "adsk::fusion::ConstructionPlane":
        # TODO: Coordinate in assembly context, world transform still required!
        return planeEntity.geometry
    elif planeEntity.objectType == "adsk::fusion::Profile":
        return adsk.core.Plane.createUsingDirections(
            adsk.core.Point3D.create(0,0,0),
            planeEntity.parentSketch.xDirection,
            planeEntity.parentSketch.yDirection
        )
    elif planeEntity.objectType == "adsk::fusion::BRepFace":
        _, normal = planeEntity.evaluator.getNormalAtPoint(planeEntity.pointOnFace)
        return adsk.core.Plane.create(
            adsk.core.Point3D.create(0,0,0),
            normal
        )

def selectedOrigin(ddOrigin):
    originEntity = ddOrigin.selection(0).entity
    if originEntity.objectType == "adsk::fusion::SketchPoint":
        return originEntity.worldGeometry
    elif originEntity.objectType == "adsk::fusion::ConstructionPoint":
        # TODO: Coordinate in assembly context, world transform still required!
        return originEntity.geometry
    elif originEntity.objectType == "adsk::fusion::BRepVertex":
        return originEntity.geometry
```

I have some code [Here](https://github.com/NicoSchlueter/Reverse/blob/a955971728648834122b594269257b08fb59ace6/Reverse.py#L253) that might fix that, but haven't tried it yet.

also changed planeAndOriginToMatrix3D as I felt like setToAlignCoordinateSystems did the same thing, however not sure if you had a reason to make it more complex

```
def planeAndOriginToMatrix3D(plane, origin):
    matrix = adsk.core.Matrix3D.create()
    matrix.setToAlignCoordinateSystems(
        adsk.core.Point3D.create(0,0,0),
        adsk.core.Vector3D.create(1,0,0),
        adsk.core.Vector3D.create(0,1,0),
        adsk.core.Vector3D.create(0,0,1),
        origin,
        plane.uDirection,
        plane.vDirection,
        plane.normal
        )
    return matrix
```

**Comment by lhns** [comment]
Actually the matrix.setToAlignCoordinateSystems method was just what I was looking for ^^. Must have overlooked it.

**Comment by lhns** [comment]
I have renamed the "origin" to "center". I think it is more convenient if the gear gets placed on the selected plane and not directly on the center point because it makes it easier to place gears on top of other surfaces. The point where the gear is actually placed is determined by an orthogonal line through the plane and the center point.
I don't know if this is the best solution. Certainly not for rack gears. It would probably make more sense for rack gears to select a line instead of a point.

**Comment by phossystems** [comment]
That makes sense. So gear on plane when plane-like things are selected and on center when line-like things are selected.

Racks are tricky. Plane and line sounds good.

**Comment by phossystems** [comment]
I worked on this a bit the past few weeks. Check my development branch to see if you like it. Still a lot to do but it’s becoming useable.

**Comment by phossystems** [comment]
I just finished up most of it and merged it to master. I hope it does everything how you wanted it. Thanks for your contribution!

**Pull request closed without merging**
